### ISSUE TITLE
install.sh有个地方错了

### ISSUE THREAD

**Issue by gou4shi1** [yakumioto/YaHei-Consolas-Hybrid-1.12#6]
第11行：
`wget -P /tmp/ https://github.com/yakumioto/YaHei-Consolas-Hybrid-1.12/blob/master/YaHei%20Consolas%20Hybrid%201.12.ttf`
会下载网页而不是字体文件
应该把里面的`blob`改为`raw`，即：
`wget -P /tmp/ https://github.com/yakumioto/YaHei-Consolas-Hybrid-1.12/raw/master/YaHei%20Consolas%20Hybrid%201.12.ttf`
谢谢！

**Comment by yakumioto** [comment]
已更改～。
